### ISSUE TITLE
Project 1 : make format failed

### ISSUE THREAD

**Issue by gaofanfei** [cmu-db/bustub#73]
>➜  build git:(master) ✗ make format
Traceback (most recent call last):
  File "../build_support/run_clang_format.py", line 125, in <module>
    had_err = check(args, source_dir)
  File "../build_support/run_clang_format.py", line 51, in check
    "-i"] + formatted_filenames)
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make[3]: *** [CMakeFiles/format.dir/build.make:57：CMakeFiles/format] 错误 1
make[2]: *** [CMakeFiles/Makefile2:280：CMakeFiles/format.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:287：CMakeFiles/format.dir/rule] 错误 2
make: *** [Makefile:214：format] 错误 2

**Comment by DreaMer963** [comment]
make sure you have installed clang-format and clang-tidy
